### ISSUE TITLE
Feature request: A maximium duration option in addition to a maximum number of iterations

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [nestordemeure/friedrich#33]
Just started developing a small optimisation library for my personal problem [simple_optimization](https://crates.io/crates/simple_optimization).

I'm looking to add bayesian optimisation and this seems a good possible library for using as the implementation for the gaussian process part of that.

Given a multithreaded application a `std::time::duration` alternative to `max_iter` in [GaussianProcess::fit_parameters](https://docs.rs/friedrich/0.3.3/friedrich/gaussian_process/struct.GaussianProcess.html#method.fit_parameters) would be very useful.

I might propose instead of `max_iter: usize` there could be `halt_condition: HaltCondition` where:
```rust
enum HaltCondition {
    Iteration(usize),
    Duration(std::time::duration)
}
```
applied like:
```rust
let start = std::time::Instant::now();
for i in 1.. {
    // ...
    match halt_condition {
        HaltCondition::Iteration(iter) => if i == iter { break; },
        HaltCondition::Duration(dur) => if start.elapsed() > dur { break; }
    }
}
```
I would rather just submit a pull request than ask this, but looking through the library it seems a little complex for my understanding. So I will just for now simply note this might be a useful feature.

**Comment by nestordemeure** [comment]
Thank you for your feedback!

I have little time to go back to the code but I would be open to a pull request. The code is built around the idea that the user will be using a number of iteration rather than a time so you would have to modify several files to include an halting condition (mostly `builder.rs`, `optimizer.rs` and `mod.rs`) but the modification should be relatively easy and missing files will be caught when trying to run the tests after you alter the code.

Note that the number of iterations is actually an upper bound put there for safety purposes, most of the time the GP parameters will converge much earlier.

Also, if you are going to use this GP implementation for optimization, you can add new points to an already fitted model using the [add_samples method](https://docs.rs/friedrich/0.3.3/friedrich/gaussian_process/struct.GaussianProcess.html#method.add_samples) and only refit the parameters from time to time which is much cheaper than rebuilding the model from scratch (adding new points to an existing model is an O(n^2) operation while building a new model or refitting it is O(n^3) in the number of points, obviously none of this matter if you have only few points).

**Comment by nestordemeure** [comment]
Reopening this issue as I just realized that one could just add a maximum runtime to the other stopping conditions instead of using an enum, making the modifications to the code much smaller.

I am going to implement it shortly.

**Comment by nestordemeure** [comment]
The fiting function now has a `max_time` parameter which defaults to one hour (which should be a *lot* more than needed).
