### ISSUE TITLE
Predict_mean_variance returning NaN's

### ISSUE THREAD

**Issue by s4ksb** [nestordemeure/friedrich#52]
Hi, I am trying to use the GPR by iteratively training it and then using its mean and variance prediction. My main code basically has
`function(&mut self) {
     // do stuff that requires self.gpr.predict_mean_variance
     new_sample_x = vec![...]
     new_sample_y = vec![...]
     self.gpr.add_samples(&x, &y);
     self.gpr.fit_parameters(
            true,
            true,
            1000,
            0.05,
            std::time::Duration::from_secs(3600),
        );
}`

However, this works for a few iterations, before the predict_mean_variance starts returning NaN's for both the mean and the variance. Any ideas on how to get around this issue?

Thanks
Karl

**Comment by nestordemeure** [comment]
This looks like a badly conditioned problem. You might want to try setting / increasing `cholesky_epsilon` when building your Gaussian process.

**Comment by s4ksb** [comment]
With the badly conditioned problem, when I update the interpolator as above, I get the Nan error, however if I build a new gpr from scratch using the same data set, it seems to work fine. Is this still related to the cholesky epsilon?

**Comment by nestordemeure** [comment]
Interesting, are the `nan` due to `add_sample` or `fit_parameters`?

* `add_sample` boils down to a Cholesky update algorithm, that might be made more numerically stable (but that work would have to be contributed to `nalgebra` once the exact source of the problem is found).
* `fit_parameters` does a gradient descent (plus a prior fitting and some rescaling depending on your parameters): problems here could be in the parameters (large step size) or some numerically unstable rescaling.

Do you think you could locate the operation causing the problem (and, optimally, where in the operation is the problem introduced)?

More generally, your kernel might be a bad fit for your data leading to this badly conditioned problem.
